"""Send job alert emails via Gmail SMTP."""

import os
import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

logger = logging.getLogger(__name__)

GMAIL_USER = os.getenv("GMAIL_USER", "patelsanskrati05@gmail.com")
GMAIL_APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD", "")
TO_EMAIL = os.getenv("GMAIL_USER", "patelsanskrati05@gmail.com")


def _build_html(jobs: list[dict]) -> str:
    rows = ""
    for j in jobs:
        salary = j.get("salary") or "Not disclosed"
        exp = j.get("experience") or "—"
        posted = j.get("posted") or "—"
        skills = j.get("skills") or "—"
        rows += f"""
        <tr>
          <td style="padding:10px;border-bottom:1px solid #eee;">
            <a href="{j['url']}" style="font-size:15px;font-weight:bold;color:#1a73e8;text-decoration:none;">
              {j['title']}
            </a><br>
            <span style="color:#555;font-size:13px;">🏢 {j['company']}</span><br>
            <span style="color:#777;font-size:12px;">
              📍 {j['location']} &nbsp;|&nbsp;
              💰 {salary} &nbsp;|&nbsp;
              🕐 Exp: {exp}<br>
              🛠 Skills: {skills}<br>
              📅 Posted: {posted} &nbsp;|&nbsp; 🌐 Source: {j['source']}
            </span>
          </td>
        </tr>"""

    return f"""
    <html><body style="font-family:Arial,sans-serif;background:#f5f5f5;padding:20px;">
      <div style="max-width:700px;margin:auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.1);">
        <div style="background:#1a73e8;color:#fff;padding:20px;">
          <h2 style="margin:0;">🚀 {len(jobs)} New Job Alert{"s" if len(jobs)>1 else ""} for Sanskrati</h2>
          <p style="margin:5px 0 0;opacity:0.85;font-size:13px;">{datetime.now().strftime("%A, %d %B %Y · %I:%M %p")}</p>
        </div>
        <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
          {rows}
        </table>
        <div style="padding:15px;background:#f9f9f9;font-size:11px;color:#999;text-align:center;">
          Auto-generated by Job Notification Bot · Apply manually after reviewing each listing.
        </div>
      </div>
    </body></html>"""


def _build_plain(jobs: list[dict]) -> str:
    lines = [f"🚀 {len(jobs)} new job alert(s) – {datetime.now().strftime('%d %b %Y %I:%M %p')}\n"]
    for i, j in enumerate(jobs, 1):
        lines.append(
            f"{i}. {j['title']} @ {j['company']}\n"
            f"   📍 {j['location']} | 💰 {j.get('salary','?')} | Exp: {j.get('experience','?')}\n"
            f"   🔗 {j['url']}\n"
            f"   Source: {j['source']}\n"
        )
    return "\n".join(lines)


def send(jobs: list[dict]) -> bool:
    if not jobs:
        return True
    if not GMAIL_APP_PASSWORD:
        logger.error("Email: GMAIL_APP_PASSWORD not set in .env")
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🚀 {len(jobs)} New Backend Job Alert{'s' if len(jobs) > 1 else ''} | {datetime.now().strftime('%d %b')}"
    msg["From"] = GMAIL_USER
    msg["To"] = TO_EMAIL

    msg.attach(MIMEText(_build_plain(jobs), "plain"))
    msg.attach(MIMEText(_build_html(jobs), "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_USER, TO_EMAIL, msg.as_string())
        logger.info("Email: sent alert for %d jobs to %s", len(jobs), TO_EMAIL)
        return True
    except smtplib.SMTPAuthenticationError:
        logger.error("Email: authentication failed – check GMAIL_APP_PASSWORD in .env")
    except Exception as e:
        logger.error("Email: send failed: %s", e)
    return False
