from . import (
    naukri_scraper,
    linkedin_scraper,
    indeed_scraper,
    internshala_scraper,
    timesjobs_scraper,
    shine_scraper,
    wellfound_scraper,
    glassdoor_scraper,
    foundit_scraper,
    email_jobs_scraper,
    linkedin_posts_scraper,
    cutshort_scraper,
    hirist_scraper,
    apna_scraper,
)
